# Numpy

In [3]:
import numpy as np
  
# Creating array object
arr = np.array( [[ 1, 2, 3],
                 [ 4, 2, 5]] )  
# Print dimensions of the matrix
print(arr.shape)

(2, 3)


In [2]:
# Creating 2x3 matrix initialized with zeros of type float
x = np.zeros((2,3), dtype='float')
print("x = \n", x)

# Creating 4x4 matrix initialized with ones of type int
y = np.ones((4,4), dtype='int')
print("y = \n", y)

x = 
 [[0. 0. 0.]
 [0. 0. 0.]]
y = 
 [[1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]
 [1 1 1 1]]


In [4]:
arr = np.array([[-1, 2, 0, 4],
                [4, -0.5, 6, 0],
                [2.6, 0, 7, 8],
                [3, -7, 4, 2.0]])

# indexing/slicing matrices
arr2 = arr[:2, 1:3]
print(arr2)

[[ 2.   0. ]
 [-0.5  6. ]]


## Linear Algebra using numpy

In [5]:
# element-wise arithemetic operations
x_list = [1,2,3]
# print(x_list+1) error

a = np.array(x_list)

In [5]:
# add 1 to every element
print ("Adding 1 to every element:", a+1)
  
# subtract 3 from each element
print ("Subtracting 3 from each element:", a-3)
  
# multiply each element by 10
print ("Multiplying each element by 10:", a*10)
  
# square each element
print ("Squaring each element:", a**2)
  
# modify existing array
a *= 2
print ("Doubled each element of original array:", a)

Adding 1 to every element: [2 3 4]
Subtracting 3 from each element: [-2 -1  0]
Multiplying each element by 10: [10 20 30]
Squaring each element: [1 4 9]
Doubled each element of original array: [2 4 6]


In [6]:
a = np.array([[1, 2],
            [3, 4]])
b = np.array([[5, 6],
            [7, 8]])
  
# add arrays
print ("Array sum:\n", a + b)
  
# multiply arrays (elementwise multiplication)
print ("Array multiplication:\n", a*b)
  
# matrix multiplication
print ("Matrix multiplication:\n", a.dot(b))

Array sum:
 [[ 6  8]
 [10 12]]
Array multiplication:
 [[ 5 12]
 [21 32]]
Matrix multiplication:
 [[19 22]
 [43 50]]


# Vectorization 

### Using optimal and pre-compiled functions

In [6]:
# create 2 matrices of very large size
w, h = 2000, 3000
a = np.random.rand(w, h)
b = np.random.rand(w, h)
c = np.zeros((w, h))
print(a.shape)

(2000, 3000)


In [7]:
import time

tic = time.process_time()
  
for i in range(a.shape[0]):
    for j in range(a.shape[1]):
      c[i][j]= a[i][j]*b[i][j]
  
toc = time.process_time()

print("Time taken using for loops:")
print((toc-tic)*1000, "ms")

Time taken using for loops:
3734.375 ms


In [8]:
tic = time.process_time()
  
c = a*b
  
toc = time.process_time()

print("Time taken using vectorization:")
print((toc-tic)*1000, "ms")

Time taken using vectorization:
15.625 ms
